import os,re
D="/Users/spunkart/spunk-codes/exclusive"
# Read template
with open(os.path.join(D,"freelance-rate-calculator.html")) as f: T=f.read()
# Extract CSS block (everything between <style> and </style>)
css_match=re.search(r"<style>(.*?)</style>",T,re.S)
BASE_CSS=css_match.group(1) if css_match else ""
# Extract lock gate HTML
lock_match=re.search(r"(<div class=\"lock-gate\".*?</div></div></div>)",T,re.S)
LOCK=lock_match.group(1) if lock_match else ""
# Nav
NAV="""<nav class="nav"><a href="https://spunk.codes" class="nav-brand">SPUNK.CODES</a><div class="nav-links"><a href="/store">Tools</a><a href="/exclusive-tools" class="active">Exclusive</a><a href="/store#ebook">Ebooks</a><a href="/blog">Blog</a></div></nav>"""
print("Template loaded, CSS="+str(len(BASE_CSS))+" chars")

def gate_js(slug):
    return """function checkAccess(){try{var c1=localStorage.getItem("spunk_referral_code");var c2=localStorage.getItem("spunk_ref_code");if((c1&&c1.toUpperCase()==="SPUNK")||(c2&&c2.toUpperCase()==="SPUNK")){document.getElementById("lockGate").classList.add("hidden");return}}catch(e){}document.getElementById("lockGate").classList.remove("hidden")}function submitCode(){var v=document.getElementById("codeInput").value.trim().toUpperCase();if(v==="SPUNK"){try{localStorage.setItem("spunk_referral_code",v)}catch(e){}document.getElementById("lockGate").classList.add("hidden");if(typeof gtag==="function")gtag("event","code_unlock",{tool:"%s"})}else{document.getElementById("codeError").textContent="Invalid code. Try again."}}document.getElementById("codeInput").addEventListener("keydown",function(e){if(e.key==="Enter")submitCode()});checkAccess();""" % slug

ANALYTICS="""<script async src="https://www.googletagmanager.com/gtag/js?id=G-GVNL11PEGP"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date());gtag("config","G-GVNL11PEGP");</script><script>(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y)})(window,document,"clarity","script","pn0x1z2y3w");</script><script src="/auto-monetize.js"></script>"""

XBTN="""<div id="shareXBtn" style="position:fixed;left:20px;bottom:20px;z-index:9999;"><a id="shareXLink" href="#" target="_blank" rel="noopener noreferrer" title="Share on X" style="display:flex;align-items:center;justify-content:center;width:40px;height:40px;background:rgba(255,215,0,0.15);border:1px solid rgba(255,215,0,0.3);backdrop-filter:blur(10px);border-radius:50%;text-decoration:none;transition:all 0.3s ease;cursor:pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="white"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></a></div><style>#shareXBtn a:hover{background:rgba(255,215,0,0.35)!important;border-color:rgba(255,215,0,0.6)!important;transform:scale(1.1);box-shadow:0 0 15px rgba(255,215,0,0.3)}</style>"""

def tail_js(share_text):
    return """function shareX(){window.open("https://twitter.com/intent/tweet?text="+encodeURIComponent("%s Free from @SpunkArt13 (code: SPUNK)")+"&url="+encodeURIComponent("https://spunk.codes/exclusive-tools"),"_blank")}document.addEventListener("contextmenu",function(e){e.preventDefault()});document.addEventListener("keydown",function(e){if(e.key==="F12"||(e.ctrlKey&&e.shiftKey&&(e.key==="I"||e.key==="J"))||(e.ctrlKey&&e.key==="u"))e.preventDefault()});""" % share_text

def xbtn_js(share_text):
    return """(function(){var p=location.pathname.split("/").pop()||"index.html";var u="https://spunk.codes/exclusive/"+p;var t="%s @SpunkArt13";document.getElementById("shareXLink").href="https://x.com/intent/tweet?text="+encodeURIComponent(t)+"&url="+encodeURIComponent(u)})();""" % share_text

USAGE="""<script src="/usage-tracker.js"></script>"""

FOOT="""<div class="share-cta"><h3>Found this useful?</h3><p>Share this tool with others who could benefit.</p><div style="display:flex;gap:0.75rem;justify-content:center"><button class="btn btn-sm btn-gold" onclick="shareX()">Share on X</button></div></div><footer class="footer"><div class="footer-links"><a href="/">Home</a><a href="/store">All Tools</a><a href="/exclusive-tools">Exclusive Tools</a><a href="/blog">Blog</a></div><p>&copy; 2025 SPUNK.CODES. Built for founders who ship.</p></footer></div><div class="watermark">SPUNK.CODES</div>"""

def build(fn,title,desc,og,slug,extra_css,hero_pre,hero_gold,hero_p,body,js,stxt):
    h="""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%s | SPUNK.CODES</title><meta name="description" content="%s"><meta name="robots" content="noindex, nofollow"><meta property="og:title" content="%s - SPUNK.CODES Exclusive"><meta property="og:description" content="%s"><meta property="og:type" content="website"><meta property="og:url" content="https://spunk.codes/exclusive/%s"><meta property="og:site_name" content="SPUNK.CODES"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@SpunkArt13"><link rel="canonical" href="https://spunk.codes/exclusive/%s">""" % (title,desc,title,og,slug,slug)
    h+="<style>"+BASE_CSS+extra_css+"</style></head>"
    h+="""<body><div class="bg-mesh"></div><div class="bg-grid"></div>"""+LOCK+NAV
    h+="""<div class="main"><section class="hero-section"><div class="exclusive-badge">&#128081; EXCLUSIVE TOOL</div><h1>%s <span class="gold">%s</span></h1><p>%s</p></section>""" % (hero_pre,hero_gold,hero_p)
    h+=body+FOOT
    h+="<script>"+gate_js(slug)+js+tail_js(stxt)+"</script>"
    h+=ANALYTICS+XBTN+"<script>"+xbtn_js(stxt)+"</script>"+USAGE
    h+="</body></html>"
    with open(os.path.join(D,fn),"w") as f: f.write(h)
    print(f"  {fn}: {len(h):,} bytes")

# ============ TOOL 1: AI PROMPT LIBRARY ============
T1_CSS=""".filter-bar{display:flex;gap:.75rem;flex-wrap:wrap;margin-bottom:1.5rem;align-items:center}.filter-btn{padding:.5rem 1rem;border:1px solid var(--border);border-radius:8px;background:0;color:var(--text-dim);font-size:.8rem;font-weight:600;cursor:pointer;transition:all .2s;font-family:var(--font)}.filter-btn:hover,.filter-btn.active{border-color:var(--gold);color:var(--gold);background:var(--gold-dim)}.search-box{flex:1;min-width:200px}.pc{background:rgba(13,17,23,.5);border:1px solid var(--border);border-radius:12px;padding:1.2rem;margin-bottom:.75rem;transition:border-color .2s}.pc:hover{border-color:var(--gold-border)}.ph{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;margin-bottom:.5rem}.pt{font-weight:700;font-size:.95rem}.ptg{display:inline-block;padding:2px 10px;border-radius:100px;font-size:.65rem;font-weight:700;text-transform:uppercase;letter-spacing:1px}.tm{background:rgba(255,107,107,.15);color:#ff6b6b;border:1px solid rgba(255,107,107,.3)}.tc{background:rgba(88,166,255,.15);color:#58a6ff;border:1px solid rgba(88,166,255,.3)}.tw{background:rgba(57,211,83,.15);color:#39d353;border:1px solid rgba(57,211,83,.3)}.tb{background:rgba(255,215,0,.15);color:#ffd700;border:1px solid rgba(255,215,0,.3)}.tcr{background:rgba(188,143,255,.15);color:#bc8fff;border:1px solid rgba(188,143,255,.3)}.pd{font-size:.8rem;color:var(--text-dim);margin-bottom:.75rem}.ptx{font-size:.82rem;background:rgba(13,17,23,.8);border:1px solid var(--border);border-radius:8px;padding:.75rem;white-space:pre-wrap;line-height:1.5;max-height:120px;overflow:hidden;transition:max-height .3s}.ptx.exp{max-height:2000px}.pa{display:flex;gap:.5rem;margin-top:.5rem}.cb,.eb{padding:4px 12px;border:1px solid var(--border);border-radius:6px;background:0;color:var(--text-dim);font-size:.72rem;font-weight:600;cursor:pointer;transition:all .2s;font-family:var(--font)}.cb:hover{border-color:var(--gold);color:var(--gold)}.cb.ok{border-color:var(--cyan);color:var(--cyan)}.eb:hover{border-color:var(--blue);color:var(--blue)}.pcnt{font-size:.85rem;color:var(--text-dim);margin-bottom:1rem}.pcnt strong{color:var(--gold)}"""

T1_BODY="""<div class="tool-section"><h2><span class="icon">&#128269;</span> Search and Filter</h2><div class="filter-bar"><input type="text" class="search-box" id="si" placeholder="Search prompts..."><button class="filter-btn active" onclick="fc(this,0)">All</button><button class="filter-btn" onclick="fc(this,1)">Marketing</button><button class="filter-btn" onclick="fc(this,2)">Coding</button><button class="filter-btn" onclick="fc(this,3)">Writing</button><button class="filter-btn" onclick="fc(this,4)">Business</button><button class="filter-btn" onclick="fc(this,5)">Creative</button></div><div class="pcnt" id="pcnt"></div><div id="pl"></div></div>"""
T1_JS="""var cats=["all","marketing","coding","writing","business","creative"];var cc=0,st="";var P=[{c:1,t:"Landing Page Copy",d:"Generate high-converting landing page copy.",p:"You are a direct-response copywriter. Write landing page copy for [PRODUCT/SERVICE]. Target: [AUDIENCE]. Benefit: [BENEFIT]. Include: 1) PAS headline, 2) Subheadline, 3) 3 benefit sections, 4) Social proof, 5) CTA with urgency."},{c:1,t:"Email Welcome Sequence",d:"Create a 5-email welcome sequence.",p:"Create a 5-email welcome sequence for [BUSINESS] selling [PRODUCT]. Each: Subject, Preview, Body (200 words), CTA. Day 0: Welcome. Day 1: Story. Day 3: Value. Day 5: Proof. Day 7: Offer."},{c:1,t:"Content Calendar",d:"Generate 30 days of content ideas.",p:"Create a 30-day content calendar for [BRAND] on [PLATFORM]. Each day: Type, Hook, Outline, CTA, Time. Mix: 40%% value, 25%% engagement, 20%% promo, 15%% entertainment."},{c:1,t:"Ad Copy Variants",d:"Generate 5 ad copy variants for testing.",p:"Write 5 ad variants for [PRODUCT] on [PLATFORM]. Angles: Pain, Benefit, FOMO, Curiosity, Direct offer. Each: Headline, Text, CTA."},{c:1,t:"SEO Blog Brief",d:"Create SEO blog post briefs that rank.",p:"Blog brief for [KEYWORD]. Include: Title, Meta desc, H1, Outline with H2/H3s, Word count, LSI keywords, Internal links, Featured snippet, CTA."},{c:1,t:"Product Launch Emails",d:"Build a complete 7-email launch campaign.",p:"7-email launch for [PRODUCT] at [PRICE]. Emails: Teaser, Problem, Solution, Features, Proof, FAQ, Last chance. Each: subject, body, CTA."},{c:1,t:"Competitor Analysis",d:"Systematically analyze any competitor.",p:"Analyze [COMPETITOR] in [INDUSTRY]: Positioning, Value prop, Audience, Pricing, Content, Social, SEO, Strengths, Weaknesses, Differentiation."},{c:1,t:"Customer Avatar",d:"Create detailed customer profiles.",p:"Customer avatar for [BUSINESS]: Demographics, Psychographics, Pain points (5), Goals (5), Objections (5), Online hangouts, Search behavior."},{c:1,t:"Viral Hook Generator",d:"Create scroll-stopping hooks.",p:"20 hooks for [TOPIC]. Contrarian (5), Curiosity (5), Numbers (5), Identity (5). Under 15 words each. Rank by engagement."},{c:1,t:"Referral Program",d:"Design a complete referral program.",p:"Referral program for [BUSINESS]: Structure, 3 tiers, Incentives, Email templates, Landing copy, Social messages, Anti-fraud, KPIs."}
